### ISSUE TITLE
Deprecated Config warning

### ISSUE THREAD

**Issue by asfarley** [robertwahler/win32-autogui#14]
Following the example, I get a deprecation warning when including the gem:

irb(main):001:0> require 'win32/autogui'
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/win32-autogui-0.5.2/lib/win32/autogui.rb:25:in `<module:Autogui>': Use RbConfig instead of obsolete and deprecated Config.
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/win32-autogui-0.5.2/lib/win32/autogui.rb:25:in`module:Autogui': Use RbConfig instead of obsolete and deprecated Config.
C:/Ruby21-x64/lib/ruby/gems/2.1.0/gems/win32-autogui-0.5.2/lib/win32/autogui.rb:26:in `module:Autogui': Use RbConfig instead of obsolete and deprecated Config.

**Comment by globalcitizen** [comment]
Seems to totally fail now on ruby-2.2.5p319
